# Generated by Django 4.2.3 on 2023-07-10 20:48

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import peat_uploader.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeatContractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Invalid email address"
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peat_uploader.peatcontractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeatProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("project_id", models.CharField(max_length=5, unique=True)),
                ("notes", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peat_uploader.peatcontractor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeatPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("record_id", models.IntegerField()),
                ("record_date", models.DateField()),
                (
                    "depth",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(2000),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                (
                    "main_condition",
                    models.CharField(
                        choices=[
                            ("DN", "Drained"),
                            ("MD", "Modified"),
                            ("AE", "Actively eroding"),
                            ("NN", "Near natural"),
                            ("NP", "Not peat"),
                            ("FR", "Forested"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "sub_condition",
                    models.CharField(
                        choices=[
                            ("HG", "Hagg/gully"),
                            ("FB", "Flat/bare"),
                            ("AR", "Artificial"),
                            ("GD", "Grass-dominated"),
                            ("HD", "Heather-dominated"),
                            ("RD", "Rush-dominated"),
                        ],
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField()),
                (
                    "photo",
                    django_resized.forms.ResizedImageField(
                        blank=True,
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        null=True,
                        quality=-1,
                        scale=None,
                        size=[1980, 1080],
                        upload_to=peat_uploader.models.get_upload_path,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=27700)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="peat_uploader.peatproject",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("project_id", "record_id")},
            },
        ),
    ]
